# Generated by Django 5.1.7 on 2025-06-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="external_url",
            field=models.URLField(
                blank=True, help_text="Link para a plataforma de venda", max_length=500
            ),
        ),
    ]
