# Generated by Django 5.2.1 on 2025-06-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_category_options_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="codigo_produto",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Código do Produto"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="loja",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Loja"
            ),
        ),
    ]
