# Generated by Django 5.2.1 on 2025-06-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_product_codigo_produto_product_loja"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="parcelado",
            field=models.BooleanField(
                default=False,
                help_text="Marque se o produto pode ser parcelado",
                verbose_name="Parcelado",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pix",
            field=models.BooleanField(
                default=False,
                help_text="Marque se o produto pode ser pago via Pix",
                verbose_name="Aceita Pix",
            ),
        ),
    ]
